upgrading to postal service 0.46, 0.45 had conflicts with Guava version, it threw: Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Objects.toStringHelper(Ljava/lang/Object;)Lcom/google/common/base/Objects$ToStringHelper; 	at org.gbif.common.messaging.config.MessagingConfiguration.toString(MessagingConfiguration.java:62)