removing log4j and log4j-over-slf4j dependencies, those cause the exception: java.lang.NoClassDefFoundError: Could not initialize class org.apache.log4j.Log4jLoggerFactory