java17 upgrade (#452)
* adapted occurrence to latest changes in dwc-api

* dwc-api version

* gbif-api version

* dwc-io version

* pom version

* humboldt search + events response

* fixed tests

* sort + nested queries

* changed pom version

* nested facets + refactor

* fixed test

* fixes #423

* using latest query tools

* Update gbif-api.version to 2.1.17-SNAPSHOT

* changes for Humboldt search and downloads

* fix for https://github.com/gbif/pipelines/issues/1210

* updated gbif-api version

* downloads emails adapted for events

* downloads emails adapted for events

* DownloadMetadataBuilder adapted to events

* gbif-api version

* creating HE table in dwca downloads only for events

* fixed rowType HE meta.xml downloads

* adding service to server species multimedia from occurrences

* adding media table configs for testing

* moving occurrence media config out of db config

* removing iterating on splits

* reading multimedia info from json

* lowercasing mediatype

* removing salted key

* using specific gets to avoid using scans

* using the result size as returned limit

* adding missing configs for species media table

* casing the mediatype and checking minimum of numeric parameters

* occurrence extension + interpretedExtensions param

* adapted extensions query DWCA download to use it for events

* update gbif-api version to 2.2.0-SNAPSHOT

* fixing read of total multimedia count

* return empty set for verbatim and interpreted extensions if they are null

* setting missing interpretedExtensions

* renaming speciesKey to taxonKey

* media results put in the results array

* migrate HttpServletRequest import from javax to jakarta

* SearchHitConverter: handle nested paths that contains lists

* updating metastore from the service

* making table metadata update atomic

* merging multimedia species changes from species_multimedia branch

* Support for querying taxonomic issues and fixes for isNull, isNotNull predicates (#438)

* es default checklist key fix

* test fix

* defaultChecklistKey for SQL downloads

* GbifTerm.issue array join

* GbifTerm.issue array join - syntax fix

* fix for classifications[null] error on test

* fix for classifications[null] error on test

* Events refactor (#439)

* (WIP) aux commit to save changes

* (WIP) aux commit to save changes

* (WIP) aux commit to save changes

* docs + cleanup + unused params removed

* refactor: update event sorting field and remove unused methods

* refactor: remove unused organism quantity fields and preparations from event conversion

* deleted ChildrenFieldsMapping since it's not being used

* comment out default sort for event yearMonthEventId until reindexing

* update default sorting for events to include year, month, and event ID

* adjust default sorting for events to exclude event ID

* update event handling for issue queries and adjust event API documentation

* refactor issue query handling in event and occurrence search request builders

* update humboldt taxonomic issue parameter in event search request builder

* add Swagger documentation for event downloads API

* generifyng docs for events and occurrences downloads

* update order value in EventResource docs properties

* add OpenAPI configuration for event-ws

* update order value in EventResource docs

* add GADM regions tag with description and order extension in EventResource docs

* refactor EventResource: replace CommonOffsetLimitParameters and CommonFacetParameters with EventSearchParameters

* add CommonFacetParameters annotation to OpenAPIUtils

* rename searchRequest parameter to request to hide it from docs

* added @ParameterObject to event search

* Humbold Extension search params docs

* add TODO to include datasetKey as a parameter in OccurrenceSearchRequest

* merge from DEV

* merge from DEV

* merge from DEV

* refactor OccurrenceWsItConfiguration: reorganize imports and update esFieldMapper method

* update gbif-api and gbif-common versions to remove event-specific suffixes

* update gbif-registry version to 4.1.21-SNAPSHOT

* update testcontainers-elasticsearch version to 2.0.2

* update artifactId for testcontainers-elasticsearch dependency

* refactor SparkDownloadWorkflowModuleTestIT: reorganize imports and update ElasticsearchContainer initialization

* add testcontainers dependency to pom.xml for improved testing support

* update testcontainers version in pom.xml to use testcontainers-elasticsearch.version

* update junit-jupiter version to 5.11.2 in pom.xml

* Revert "update junit-jupiter version to 5.11.2 in pom.xml"

This reverts commit 99b31621e550006440a82c8c453cb220d9e8937a.

* refactor: update test imports to JUnit 5 in ExtensionsQueryTest and GenerateHQLTest

* fix: update Elasticsearch Docker image to use the official version

* fix: update commons-lang version to 3.14.0 in pom.xml

* fixed wrong download query introduced in events merge

* nonTaxonomicIssue - isHiveArray = true

* fix: refine download query to include core term check for Humboldt search

* added superfamilyKey, subfamilyKey to recognised taxonomic terms

* fix: exclude event downloads from small download check in AirflowDownloadLauncherService

* added subtribekey

* Added DownloadTypeInterceptor to set download type to EVENT

* fix: update object mappers to use specific serializers for occurrence and event search parameters

* fix: refactor DownloadMetadataBuilderTest to improve deserializer registration

* fix: update object mappers to register event search parameter serializers

* 442 fix: add deserializers for EventSearchParameter and OccurrenceSearchParameter

* upgrading spring and other dependencies

* adding missing dependency

* adding missing dependency jakarta annotations

* upgrading gbif api

* fixing dependencies

* upgrading gbif api and adapting to ne name usage api

* upgrading janino

* upgrading apache commons libraries

* fixing: ERROR [2025-12-11 15:00:35,362+0000] [http-nio-9020-exec-8] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.ClassCastException: class io.swagger.v3.oas.models.media.JsonSchema cannot be cast to class io.swagger.v3.oas.models.media.ArraySchema (io.swagger.v3.oas.models.media.JsonSchema and io.swagger.v3.oas.models.media.ArraySchema are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @7aec35a)] with root cause
        java.lang.ClassCastException: class io.swagger.v3.oas.models.media.JsonSchema cannot be cast to class io.swagger.v3.oas.models.media.ArraySchema (io.swagger.v3.oas.models.media.JsonSchema and io.swagger.v3.oas.models.media.ArraySchema are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @7aec35a)
        	at org.gbif.occurrence.ws.config.OpenAPIConfiguration.lambda$sortTagsByOrderExtension$3(OpenAPIConfiguration.java:69)
        	at org.springdoc.api.AbstractOpenApiResource.lambda$getOpenApi$7(AbstractOpenApiResource.java:412)

* matching swagger version

* fixing version changed in spring and springdocs

* changing to snapshot version

* upgrading kvs and lombok

* upgrading jcommander and avro

* using kvs 2.0 taxonomy interpretation changed

* removing unused import and updating gbif common library

* Events review mappings taxon (#448)

* fix: update taxonomic fields and descriptions in OpenAPIUtils and related classes

* fix: add collectionCode parameter to OpenAPIUtils and EventEsField

* fix: remove unused otherCatalogNumbers and coordinateAccuracy fields from interpretedEvent

* fix: update event search parameters for consistency in usage key references

* EventHDFSTableDefinition + event own terms for downloads

* fix: update interpreted headers to use Occurrence term for small downloads

* fix: refactor taxon classification mapping to use nested usage structures

* fix: update taxon classification to use iucnRedListCategoryCode instead of iucnRedListCategory

* fix: update event HDFS table definition to exclude interpreted terms

* fix: optimize internal terms handling by removing interpreted terms from the set

* feat: add EventsHiveQueries for generating TSV downloads and integrate with query execution

* fix: refactor query selection logic to use a dedicated method for core term handling

* feat: add derived taxon IDs and classifications to Hive data types and occurrence table definition

* fix: remove unused taxonomic classification fields from EventEsField

* fix: remove unused classification parameters from OpenAPIUtils

* rollback derived taxon(waiting for spark pipelines)

* fix: update EventDownloadTerms to use eventID and parentEventID instead of occurrenceID

* fix: update validation imports from javax to jakarta in configuration files

* fix: add eventID to EventTermUtils

* fix: add locality term to EventTermUtils

* fix: remove individualCount from Event simple csv download

* fix: add institutionCode and collectionCode to EventTermUtils

* fix: update version in pom.xml to remove '-events' suffix

* formatting

* fix: update EventTermUtils to filter out terms populated by interpretation and add unit tests

* fix: update gbif-api, gbif-registry, and gbif-predicates versions in pom.xml

* upgrading parsers versio to match pipelines version

* uphrading dependencies to match pipelines project

* minor upgrades

* fix: update event ID queries to remove unnecessary keyword suffix

* fix: update gbif-postal-service version to 2.1.4-SNAPSHOT

* matching version of gbif cli and using logstash encoder 8.1, 9s requires jackson 3

* upgrading cli and moving version to properties

* upgrading common mybatis

* excluding reload4j

* fixed download of interpreted extensions events

* fix: update core term reference in HQL generation for occurrence fields

* fixed OpenAPI docs

* fix: add datasetKey parameter to OccurrenceSearchRequest if available

* fix: correct field name in defaultSort for event yearMonthEventID

* removed ToDo because the proposal can't be done

* fix: update OccurrenceSearchService to use occurrenceWsSearchClient and fixed event occurrences search

* #430 delete table files (#451)

* set Spark log level to DEBUG in TableBackfill

* set Spark log level to DEBUG in TableBackfill

* use timestamp for table prefix

* delete table files manually

* delete table files manually

* delete table files manually

* PR feedback

* update gbif-api version to 2.2.3-SNAPSHOT

* update gbif-common-ws version to 2.1.2-SNAPSHOT

* adapted DownloadMetadataBuilder and OccurrenceEmailManager to events

* migrate validation imports from javax to jakarta

* migrate validation imports from javax to jakarta

* upgrading gbif dependencies to release version, removing geotools unsued dependencies

* upgrading geotools version and some other dependencies

* Update gbif-occurrence-cube-functions version to 1.0.1

* typo fix in pom

* dependency upgrades

* removing javax.annotation and upgrading gbif dependencies

* updating to latest gbif releases of registry and dwca-io

---------

Co-authored-by: Marcos Lopez Gonzalez <marcoslg@gmail.com>
Co-authored-by: Dave Martin <djtfmartin@users.noreply.github.com>
Co-authored-by: Dave Martin <djtfmartin@gmail.com>
Co-authored-by: fmendezh <federicomh@gmail.com>
Co-authored-by: Marcos Lopez Gonzalez <asturcon1234@gmail.com>
Co-authored-by: Matt Blissett <mblissett@gbif.org>